#cloud-config
users:
  - name: ${username}
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    lock_passwd: true
    ssh_authorized_keys:
      - ${ssh_public_key}

package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - git
  - unzip
  - htop
  - vim
  - docker.io
  - ufw

write_files:
  - path: /tmp/k3s-install.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      set -e
      
      # Update system
      apt-get update -y
      apt-get upgrade -y
      
      # Configure firewall
      ufw allow 22/tcp
      ufw allow 6443/tcp
      ufw allow 80/tcp
      ufw allow 443/tcp
      ufw allow 8080/tcp
      ufw allow 10250/tcp
      ufw allow 8472/udp
      ufw allow 10254/tcp
      ufw --force enable
      
      # Add user to docker group
      usermod -aG docker ${username}
      systemctl enable docker
      systemctl start docker
      
      # Wait for master to be ready
      sleep 120
      
      # Get K3s token from master
      K3S_TOKEN=$(ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${username}@${master_ip} "sudo cat /var/lib/rancher/k3s/server/node-token" 2>/dev/null || echo "")
      
      if [ -z "$K3S_TOKEN" ]; then
        echo "Failed to get K3s token from master, trying alternative method..."
        sleep 60
        K3S_TOKEN=$(ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${username}@${master_ip} "sudo cat /var/lib/rancher/k3s/server/node-token" 2>/dev/null || echo "")
      fi
      
      if [ -n "$K3S_TOKEN" ]; then
        # Install K3s agent
        curl -sfL https://get.k3s.io | K3S_URL=https://${master_ip}:6443 K3S_TOKEN=$K3S_TOKEN sh -
        echo "K3s worker installation completed"
      else
        echo "Failed to get K3s token from master node"
        exit 1
      fi

runcmd:
  - /tmp/k3s-install.sh

final_message: "K3s worker node setup completed"