#cloud-config
users:
  - name: ${username}
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    lock_passwd: true
    ssh_authorized_keys:
      - ${ssh_public_key}

package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - git
  - unzip
  - htop
  - vim
  - docker.io
  - ufw

write_files:
  - path: /tmp/k3s-install.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      set -e
      
      # Update system
      apt-get update -y
      apt-get upgrade -y
      
      # Configure firewall
      ufw allow 22/tcp
      ufw allow 6443/tcp
      ufw allow 80/tcp
      ufw allow 443/tcp
      ufw allow 8080/tcp
      ufw allow 10250/tcp
      ufw allow 8472/udp
      ufw allow 10254/tcp
      ufw --force enable
      
      # Add user to docker group
      usermod -aG docker ${username}
      systemctl enable docker
      systemctl start docker
      
      # Install K3s server
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644 --disable traefik --disable servicelb --cluster-init" sh -
      
      # Wait for K3s to be ready
      sleep 30
      
      # Create kubeconfig for user
      mkdir -p /home/${username}/.kube
      cp /etc/rancher/k3s/k3s.yaml /home/${username}/.kube/config
      chown ${username}:${username} /home/${username}/.kube/config
      
      # Install kubectl
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl"
      chmod +x kubectl
      mv kubectl /usr/local/bin/
      
      # Install Helm
      curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      
      # Install Nginx Ingress Controller
      kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.2/deploy/static/provider/cloud/deploy.yaml
      
      # Wait for ingress controller to be ready
      kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=300s || true
      
      echo "K3s master installation completed"

runcmd:
  - /tmp/k3s-install.sh

final_message: "K3s master node setup completed"