apiVersion: v2
name: code-server
description: A Helm chart for deploying code-server on Kubernetes
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - code-server
  - vscode
  - development
  - ide
home: https://github.com/idvoretskyi/oci-code-server-arm
sources:
  - https://github.com/coder/code-server
maintainers:
  - name: maintainer
    email: maintainer@example.com
dependencies: []
annotations:
  category: Development