# Default values for code-server
# This is a YAML-formatted file.

# Image configuration
image:
  repository: codercom/code-server
  tag: "latest"
  pullPolicy: Always

# Deployment configuration
replicaCount: 1

# Service configuration
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/websocket-services: "code-server-service"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: code-server.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: code-server-tls
      hosts:
        - code-server.yourdomain.com

# Persistent storage configuration
persistence:
  enabled: true
  storageClass: local-storage
  accessMode: ReadWriteOnce
  size: 10Gi
  hostPath: /opt/code-server-data
  nodeSelector:
    kubernetes.io/hostname: k3s-master-1

# Code-server configuration
codeServer:
  password: "YOUR-SECURE-PASSWORD-HERE"  # CHANGE THIS! Set a secure password
  config:
    bind-addr: "0.0.0.0:8080"
    auth: "password"
    cert: false
    disable-telemetry: true
    disable-update-check: true
    disable-file-downloads: false
    disable-file-uploads: false
    user-data-dir: "/home/coder/.local/share/code-server"
    extensions-dir: "/home/coder/.local/share/code-server/extensions"
    log: "info"
  
  # VS Code settings
  settings:
    workbench.colorTheme: "Dark+ (default dark)"
    terminal.integrated.shell.linux: "/bin/bash"
    extensions.autoUpdate: false
    extensions.autoCheckUpdates: false
    telemetry.telemetryLevel: "off"
    workbench.startupEditor: "none"
    git.autofetch: true
    files.autoSave: "onFocusChange"
    editor.formatOnSave: true
    editor.tabSize: 2
    editor.insertSpaces: true
    files.trimTrailingWhitespace: true
    files.insertFinalNewline: true

# Environment variables
env:
  TZ: "UTC"
  USER: "coder"
  DEFAULT_WORKSPACE: "/home/coder/workspace"

# Resource limits
resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "2000m"

# Security context
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

# Pod security context
podSecurityContext:
  fsGroup: 1000

# Health checks
livenessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 10

readinessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5

# Node selection
nodeSelector:
  kubernetes.io/hostname: k3s-master-1

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Docker socket access
dockerSocket:
  enabled: true
  hostPath: /var/run/docker.sock

# Namespace
namespace: code-server

# Additional labels
labels: {}

# Additional annotations
annotations: {}

# Service account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod annotations
podAnnotations: {}

# Pod labels
podLabels: {}