apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "code-server.fullname" . }}-config
  namespace: {{ include "code-server.namespace" . }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- range $key, $value := .Values.codeServer.config }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  settings.json: |
    {
      {{- $settings := .Values.codeServer.settings }}
      {{- $keys := keys $settings | sortAlpha }}
      {{- range $i, $key := $keys }}
      "{{ $key }}": {{ index $settings $key | toJson }}{{ if lt $i (sub (len $keys) 1) }},{{ end }}
      {{- end }}
    }