apiVersion: v1
kind: Secret
metadata:
  name: {{ include "code-server.fullname" . }}-secret
  namespace: {{ include "code-server.namespace" . }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.codeServer.password | b64enc | quote }}