apiVersion: v1
kind: Service
metadata:
  name: {{ include "code-server.fullname" . }}-service
  namespace: {{ include "code-server.namespace" . }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "code-server.selectorLabels" . | nindent 4 }}