name: OpenTofu Lint and Validate

on:
  push:
    branches: [main]
    paths:
      - 'tofu/**/*.tf'
      - 'tofu/**/*.tfvars'
      - '.github/workflows/opentofu-lint.yml'
  pull_request:
    branches: [main]
    paths:
      - 'tofu/**/*.tf'
      - 'tofu/**/*.tfvars'
      - '.github/workflows/opentofu-lint.yml'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  tflint:
    name: TFLint with OpenTofu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: latest

      - name: Initialize TFLint
        run: tflint --init
        working-directory: tofu

      - name: Run TFLint
        run: tflint --format=compact --recursive
        working-directory: tofu

      - name: OpenTofu fmt check
        run: tofu fmt -check -recursive
        working-directory: tofu
        continue-on-error: true

      - name: OpenTofu init
        run: tofu init -backend=false
        working-directory: tofu

      - name: OpenTofu validate
        run: tofu validate
        working-directory: tofu
