name: Shell Script Linting

on:
  push:
    branches: [main]
    paths:
      - '**.sh'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    branches: [main]
    paths:
      - '**.sh'
      - '.github/workflows/shellcheck.yml'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'
          severity: warning
          format: gcc
        env:
          SHELLCHECK_OPTS: -e SC1091 -e SC2034

      - name: Run ShellCheck with SARIF output
        uses: ludeeus/action-shellcheck@master
        continue-on-error: true
        with:
          scandir: '.'
          severity: warning
          format: sarif
        env:
          SHELLCHECK_OPTS: -e SC1091 -e SC2034

      - name: Ensure SARIF file exists
        run: |
          if [ ! -f shellcheck.sarif ]; then
            echo '{"version":"2.1.0","runs":[]}' > shellcheck.sarif
          fi

      - name: Upload ShellCheck SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: shellcheck.sarif
