name: Shell Script Linting

on:
  push:
    branches: [main]
    paths:
      - '**.sh'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    branches: [main]
    paths:
      - '**.sh'
      - '.github/workflows/shellcheck.yml'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'
          severity: warning
          format: gcc
        env:
          SHELLCHECK_OPTS: -e SC1091 -e SC2034

      - name: Run ShellCheck with SARIF output
        uses: ludeeus/action-shellcheck@master
        continue-on-error: true
        with:
          scandir: '.'
          severity: warning
          format: sarif
        env:
          SHELLCHECK_OPTS: -e SC1091 -e SC2034

      - name: Check if SARIF file has findings
        id: check_sarif
        run: |
          if [ ! -f shellcheck.sarif ]; then
            echo "has_findings=false" >> $GITHUB_OUTPUT
          elif [ ! -s shellcheck.sarif ]; then
            echo "has_findings=false" >> $GITHUB_OUTPUT
          elif grep -q '"runs":\[\]' shellcheck.sarif || ! grep -q '"results"' shellcheck.sarif; then
            echo "has_findings=false" >> $GITHUB_OUTPUT
          else
            echo "has_findings=true" >> $GITHUB_OUTPUT
          fi

      - name: Upload ShellCheck SARIF results
        if: steps.check_sarif.outputs.has_findings == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: shellcheck.sarif
