name: YAML Lint

on:
  push:
    branches: [main]
    paths:
      - '**.yml'
      - '**.yaml'
      - '.github/workflows/yaml-lint.yml'
  pull_request:
    branches: [main]
    paths:
      - '**.yml'
      - '**.yaml'
      - '.github/workflows/yaml-lint.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  yamllint:
    name: YAML Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: pip install yamllint

      - name: Create yamllint config
        run: |
          cat > .yamllint.yml << EOF
          extends: default
          rules:
            line-length:
              max: 120
              level: warning
            indentation:
              spaces: 2
              indent-sequences: true
            comments:
              min-spaces-from-content: 1
            document-start: disable
            truthy:
              allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
              check-keys: false
          ignore: |
            .git/
            tofu/.terraform/
          EOF

      - name: Run yamllint
        run: yamllint -f colored .
